name:  Continuous Deployment (CD)

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:

  build:
    name: Build Project
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions: write-all
    with:
      release: true

  release:
    needs: build
    name: Release Project
    uses: ./.github/workflows/release.yml
    secrets: inherit
    permissions: write-all